### ISSUE TITLE
I am getting error while compiling the code.

### ISSUE THREAD

**Issue by Daanishh** [debsahu/DDUpdateUploadServer#1]
*** [.pio\build\nodemcuv2-mqtt\src\DDUpdateUploadServer.cpp.o] Error 1
In file included from C:/Users/Danish Hussain/Desktop/PCF8574_8Relay-master/Arduino/PCF8574_8Relay/PCF8574_8Relay.ino:28:0:
Arduino\PCF8574_8Relay/DDUpdateUploadServer.h:15:7: error: using typedef-name 'using ESP8266WebServer = class esp8266webserver::ESP8266WebServerTemplate<WiFiServer>' after 'class'
 class ESP8266WebServer;

Can you help me with this ?

**Comment by debsahu** [comment]
I updated the platformio.ini file here: https://github.com/debsahu/PCF8574_8Relay/commit/2b9a959e36945a69a6dc5e97d32d8def5e5eed6b This should fix the compilation issue.

**Comment by davdav42** [comment]
Hello I have exactly the same issue.
The platformio.ini seems to be up to date. Could you help me?

In file included from D:\domotique\Fils Pilote\PCF8574_8Relay-master\Arduino\PCF8574_8Relay\PCF8574_8Relay.ino:28:0:

C:\Users\David\Documents\Arduino\libraries\DDUpdateUploadServer-master\src/DDUpdateUploadServer.h:15:7: error: using typedef-name 'using ESP8266WebServer = class esp8266webserver::ESP8266WebServerTemplate<WiFiServer>' after 'class'

 class ESP8266WebServer;

       ^

In file included from D:\domotique\Fils Pilote\PCF8574_8Relay-master\Arduino\PCF8574_8Relay\PCF8574_8Relay.ino:11:0:

C:\Users\David\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WebServer\src/ESP8266WebServer.h:261:80: note: 'using ESP8266WebServer = class esp8266webserver::ESP8266WebServerTemplate<WiFiServer>' has a previous declaration here

 using ESP8266WebServer = esp8266webserver::ESP8266WebServerTemplate<WiFiServer>;

                                                                                ^

exit status 1
Erreur de compilation pour la carte Generic ESP8266 Module

**Comment by davdav42** [comment]
I think I Have a duplicate declaration of class ESP8266WebServer (In this file and in ESP8266WebServer.h). I rename it in DDUpdateUploadServer by ESP8266WebServer**2** and I could compile.
But I'm not sure how to do?

**Comment by davdav42** [comment]
Sorry I didn't see your answer on  '44c7a26'
So It was this I had a double declaration.
Thank you very much!!!
